resilience4j.ratelimiter:
  instances:
    how_old_api:
      limitForPeriod: 3
      limitRefreshPeriod: 5s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100
